name: "build"
on: [push, pull_request]
jobs:
  launch-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: Install gems
        continue-on-error: true
        run: |
          gem install bundler
          bundler install
      - name: Build
        run: |
          chmod +x *.sh
          ./build.sh
          cd _site
          zip -r ../website.zip *
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MF_PAT }}
        with:
          source-directory: '.'
          destination-github-username: 'matteo-francia'
          destination-repository-name: 'matteo-francia.github.io'
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MF2_PAT }}
        with:
          source-directory: '.'
          destination-github-username: 'mttfrn'
          destination-repository-name: 'mttfrn.github.io'
